// Discover Items - Itineraries and Audio Guides
export interface DiscoverItem {
  id: string
  type: 'itinerary' | 'audio-guide' | 'route'
  title: string
  destination: string
  duration: string
  description: string
  likes: number
  saves: number
  views: number
  image?: string
  author?: string
  rating?: number
  locations?: number // For itineraries
  audioLength?: string // For audio guides
}

export const discoverItems: DiscoverItem[] = [
  // Itineraries
  {
    id: 'itinerary-1',
    type: 'itinerary',
    title: 'Perfect 5-Day Tokyo Itinerary',
    destination: 'Tokyo, Japan',
    duration: '5 days',
    description: 'A comprehensive guide to Tokyo covering temples, markets, modern districts, and hidden gems. Perfect for first-time visitors.',
    likes: 234,
    saves: 89,
    views: 1200,
    author: 'Traveler123',
    rating: 4.8,
    locations: 15,
  },
  {
    id: 'itinerary-2',
    type: 'itinerary',
    title: 'Kyoto Cultural Journey',
    destination: 'Kyoto, Japan',
    duration: '4 days',
    description: 'Explore ancient temples, traditional gardens, and authentic Japanese culture in the former imperial capital.',
    likes: 189,
    saves: 92,
    views: 1100,
    author: 'CultureSeeker',
    rating: 4.7,
    locations: 12,
  },
  {
    id: 'itinerary-3',
    type: 'itinerary',
    title: 'London Highlights in 3 Days',
    destination: 'London, UK',
    duration: '3 days',
    description: 'See the best of London: Tower Bridge, British Museum, Westminster Abbey, and more iconic landmarks.',
    likes: 312,
    saves: 145,
    views: 2100,
    author: 'LondonExplorer',
    rating: 4.9,
    locations: 10,
  },
  {
    id: 'itinerary-4',
    type: 'itinerary',
    title: 'Paris Romantic Getaway',
    destination: 'Paris, France',
    duration: '4 days',
    description: 'Romantic spots, world-class museums, and charming neighborhoods. Perfect for couples.',
    likes: 278,
    saves: 134,
    views: 1800,
    author: 'ParisLover',
    rating: 4.8,
    locations: 14,
  },
  {
    id: 'itinerary-5',
    type: 'itinerary',
    title: 'Barcelona Food & Culture Tour',
    destination: 'Barcelona, Spain',
    duration: '5 days',
    description: 'Discover Gaudi architecture, tapas bars, beaches, and vibrant Catalan culture.',
    likes: 201,
    saves: 98,
    views: 1500,
    author: 'FoodieTravel',
    rating: 4.6,
    locations: 18,
  },
  {
    id: 'itinerary-6',
    type: 'itinerary',
    title: 'New York City Essentials',
    destination: 'New York, USA',
    duration: '6 days',
    description: 'Manhattan highlights: Central Park, Broadway, museums, and iconic neighborhoods.',
    likes: 445,
    saves: 201,
    views: 3200,
    author: 'NYCGuide',
    rating: 4.9,
    locations: 20,
  },
  {
    id: 'itinerary-7',
    type: 'itinerary',
    title: 'Rome Historical Walk',
    destination: 'Rome, Italy',
    duration: '4 days',
    description: 'Ancient ruins, Vatican City, and authentic Italian cuisine in the Eternal City.',
    likes: 267,
    saves: 123,
    views: 1900,
    author: 'HistoryBuff',
    rating: 4.7,
    locations: 13,
  },
  {
    id: 'itinerary-8',
    type: 'itinerary',
    title: 'Bali Island Adventure',
    destination: 'Bali, Indonesia',
    duration: '7 days',
    description: 'Temples, rice terraces, beaches, and traditional Balinese culture.',
    likes: 334,
    saves: 167,
    views: 2400,
    author: 'IslandHopper',
    rating: 4.8,
    locations: 16,
  },
  
  // Audio Guides
  {
    id: 'audio-1',
    type: 'audio-guide',
    title: 'Senso-ji Temple Audio Guide',
    destination: 'Tokyo, Japan',
    duration: '15 min',
    description: 'Learn about Tokyo\'s oldest temple, its history, architecture, and cultural significance.',
    likes: 156,
    saves: 67,
    views: 890,
    author: 'TokyoGuide',
    rating: 4.7,
    audioLength: '15:30',
  },
  {
    id: 'audio-2',
    type: 'audio-guide',
    title: 'Tower of London Walking Tour',
    destination: 'London, UK',
    duration: '25 min',
    description: 'Discover the Crown Jewels, ravens, and 1000 years of royal history.',
    likes: 223,
    saves: 98,
    views: 1450,
    author: 'LondonVoice',
    rating: 4.9,
    audioLength: '25:15',
  },
  {
    id: 'audio-3',
    type: 'audio-guide',
    title: 'Eiffel Tower & Surroundings',
    destination: 'Paris, France',
    duration: '20 min',
    description: 'History of the iconic tower and stories of the surrounding Champ de Mars.',
    likes: 189,
    saves: 87,
    views: 1200,
    author: 'ParisAudio',
    rating: 4.8,
    audioLength: '20:45',
  },
  {
    id: 'audio-4',
    type: 'audio-guide',
    title: 'Sagrada Familia Architecture Tour',
    destination: 'Barcelona, Spain',
    duration: '30 min',
    description: 'Deep dive into Gaudi\'s masterpiece: symbolism, design, and construction history.',
    likes: 178,
    saves: 76,
    views: 1100,
    author: 'ArchitectureLover',
    rating: 4.6,
    audioLength: '30:20',
  },
  {
    id: 'audio-5',
    type: 'audio-guide',
    title: 'Central Park Stories',
    destination: 'New York, USA',
    duration: '18 min',
    description: 'Hidden stories, famous landmarks, and natural history of Manhattan\'s green heart.',
    likes: 145,
    saves: 65,
    views: 980,
    author: 'NYCStories',
    rating: 4.7,
    audioLength: '18:10',
  },
  {
    id: 'audio-6',
    type: 'audio-guide',
    title: 'Colosseum & Roman Forum',
    destination: 'Rome, Italy',
    duration: '22 min',
    description: 'Ancient gladiator battles, emperors, and the heart of the Roman Empire.',
    likes: 201,
    saves: 94,
    views: 1350,
    author: 'RomanHistory',
    rating: 4.8,
    audioLength: '22:30',
  },
  {
    id: 'audio-7',
    type: 'audio-guide',
    title: 'Ubud Rice Terraces Walk',
    destination: 'Bali, Indonesia',
    duration: '12 min',
    description: 'Traditional farming methods, local culture, and stunning landscapes.',
    likes: 134,
    saves: 58,
    views: 870,
    author: 'BaliNature',
    rating: 4.5,
    audioLength: '12:15',
  },
  {
    id: 'audio-8',
    type: 'audio-guide',
    title: 'Fushimi Inari Shrine Path',
    destination: 'Kyoto, Japan',
    duration: '16 min',
    description: 'Walk through thousands of torii gates while learning about Shinto traditions.',
    likes: 167,
    saves: 72,
    views: 1050,
    author: 'KyotoSpirit',
    rating: 4.7,
    audioLength: '16:45',
  },
  
  // Routes
  {
    id: 'route-1',
    type: 'route',
    title: 'Historic Kyoto Walking Route',
    destination: 'Kyoto, Japan',
    duration: '3 hours',
    description: 'Optimized circular route connecting temples, shrines, and traditional streets.',
    likes: 189,
    saves: 92,
    views: 1100,
    author: 'RouteMaster',
    rating: 4.8,
    locations: 8,
  },
  {
    id: 'route-2',
    type: 'route',
    title: 'London Thames Riverside Walk',
    destination: 'London, UK',
    duration: '2.5 hours',
    description: 'Scenic walk along the Thames from Tower Bridge to Westminster.',
    likes: 156,
    saves: 78,
    views: 950,
    author: 'LondonWalker',
    rating: 4.6,
    locations: 6,
  },
  {
    id: 'route-3',
    type: 'route',
    title: 'Paris Left Bank Art Walk',
    destination: 'Paris, France',
    duration: '4 hours',
    description: 'Explore Montmartre, art galleries, and bohemian cafes in the artistic heart of Paris.',
    likes: 201,
    saves: 112,
    views: 1350,
    author: 'ArtExplorer',
    rating: 4.7,
    locations: 9,
  },
  {
    id: 'route-4',
    type: 'route',
    title: 'Barcelona Gothic Quarter Tour',
    destination: 'Barcelona, Spain',
    duration: '2 hours',
    description: 'Medieval streets, hidden plazas, and historic architecture in the old city center.',
    likes: 178,
    saves: 89,
    views: 1200,
    author: 'BarcelonaGuide',
    rating: 4.8,
    locations: 7,
  },
  {
    id: 'itinerary-9',
    type: 'itinerary',
    title: 'Istanbul Crossroads Tour',
    destination: 'Istanbul, Turkey',
    duration: '5 days',
    description: 'Where East meets West: Hagia Sophia, Grand Bazaar, Bosphorus cruise, and Turkish delights.',
    likes: 289,
    saves: 145,
    views: 2100,
    author: 'IstanbulExplorer',
    rating: 4.8,
    locations: 17,
  },
  {
    id: 'itinerary-10',
    type: 'itinerary',
    title: 'Dubai Modern Marvels',
    destination: 'Dubai, UAE',
    duration: '4 days',
    description: 'Burj Khalifa, Palm Jumeirah, desert safari, and luxury shopping in the city of superlatives.',
    likes: 312,
    saves: 178,
    views: 2800,
    author: 'DubaiLuxury',
    rating: 4.9,
    locations: 12,
  },
  {
    id: 'audio-9',
    type: 'audio-guide',
    title: 'Machu Picchu Sacred Valley',
    destination: 'Cusco, Peru',
    duration: '28 min',
    description: 'Inca history, architecture secrets, and the spiritual significance of this ancient wonder.',
    likes: 234,
    saves: 112,
    views: 1650,
    author: 'IncaHistory',
    rating: 4.9,
    audioLength: '28:45',
  },
  {
    id: 'audio-10',
    type: 'audio-guide',
    title: 'Sydney Harbour Bridge Walk',
    destination: 'Sydney, Australia',
    duration: '14 min',
    description: 'Engineering marvel, harbor views, and stories of the iconic bridge connecting Sydney.',
    likes: 167,
    saves: 78,
    views: 1100,
    author: 'SydneyVoice',
    rating: 4.6,
    audioLength: '14:20',
  },
  
  // More Earlier Created Audio Guides
  {
    id: 'audio-11',
    type: 'audio-guide',
    title: 'Golden Gate Bridge History Tour',
    destination: 'San Francisco, USA',
    duration: '19 min',
    description: 'The story behind one of the world\'s most photographed bridges and its role in connecting the Bay Area.',
    likes: 198,
    saves: 95,
    views: 1420,
    author: 'BayAreaGuide',
    rating: 4.7,
    audioLength: '19:30',
  },
  {
    id: 'audio-12',
    type: 'audio-guide',
    title: 'Notre-Dame Cathedral Restoration Story',
    destination: 'Paris, France',
    duration: '24 min',
    description: 'Learn about the cathedral\'s history, the 2019 fire, and the ongoing restoration efforts.',
    likes: 245,
    saves: 118,
    views: 1780,
    author: 'ParisHeritage',
    rating: 4.8,
    audioLength: '24:15',
  },
  {
    id: 'audio-13',
    type: 'audio-guide',
    title: 'Acropolis & Parthenon Ancient Athens',
    destination: 'Athens, Greece',
    duration: '27 min',
    description: 'Explore the birthplace of democracy and Western civilization on this comprehensive audio tour.',
    likes: 289,
    saves: 145,
    views: 2100,
    author: 'GreekHistory',
    rating: 4.9,
    audioLength: '27:45',
  },
  {
    id: 'audio-14',
    type: 'audio-guide',
    title: 'Venice Grand Canal Boat Tour',
    destination: 'Venice, Italy',
    duration: '22 min',
    description: 'Navigate the Grand Canal while learning about Venetian architecture, history, and culture.',
    likes: 267,
    saves: 132,
    views: 1950,
    author: 'VenetianVoice',
    rating: 4.8,
    audioLength: '22:20',
  },
  {
    id: 'audio-15',
    type: 'audio-guide',
    title: 'Petra Ancient City Walk',
    destination: 'Petra, Jordan',
    duration: '35 min',
    description: 'Discover the secrets of the Rose City, from the Siq to the Treasury and beyond.',
    likes: 312,
    saves: 167,
    views: 2350,
    author: 'MiddleEastExplorer',
    rating: 4.9,
    audioLength: '35:10',
  },
  
  // More Earlier Created Itineraries
  {
    id: 'itinerary-11',
    type: 'itinerary',
    title: 'Amsterdam Canals & Culture',
    destination: 'Amsterdam, Netherlands',
    duration: '4 days',
    description: 'Explore the city of canals: museums, historic houses, and vibrant neighborhoods.',
    likes: 256,
    saves: 134,
    views: 1950,
    author: 'DutchExplorer',
    rating: 4.7,
    locations: 14,
  },
  {
    id: 'itinerary-12',
    type: 'itinerary',
    title: 'Prague Medieval Charm',
    destination: 'Prague, Czech Republic',
    duration: '3 days',
    description: 'Castle, Charles Bridge, Old Town Square, and the best of Czech culture.',
    likes: 223,
    saves: 112,
    views: 1680,
    author: 'PragueGuide',
    rating: 4.8,
    locations: 11,
  },
  {
    id: 'itinerary-13',
    type: 'itinerary',
    title: 'Singapore Modern Marvels',
    destination: 'Singapore',
    duration: '5 days',
    description: 'Gardens by the Bay, Marina Bay Sands, and the perfect blend of culture and modernity.',
    likes: 278,
    saves: 145,
    views: 2100,
    author: 'SingaporeLover',
    rating: 4.8,
    locations: 16,
  },
  {
    id: 'itinerary-14',
    type: 'itinerary',
    title: 'Vienna Imperial Splendor',
    destination: 'Vienna, Austria',
    duration: '4 days',
    description: 'Palaces, classical music, coffee culture, and the grandeur of the Habsburg Empire.',
    likes: 234,
    saves: 123,
    views: 1820,
    author: 'ViennaClassic',
    rating: 4.7,
    locations: 13,
  },
  {
    id: 'itinerary-15',
    type: 'itinerary',
    title: 'Seoul K-Pop & Tradition',
    destination: 'Seoul, South Korea',
    duration: '6 days',
    description: 'Modern districts, ancient palaces, K-pop culture, and incredible Korean cuisine.',
    likes: 301,
    saves: 178,
    views: 2650,
    author: 'SeoulExplorer',
    rating: 4.9,
    locations: 19,
  },
  {
    id: 'itinerary-16',
    type: 'itinerary',
    title: 'Lisbon Hills & Tiles',
    destination: 'Lisbon, Portugal',
    duration: '4 days',
    description: 'Historic trams, colorful tiles, fado music, and stunning viewpoints across seven hills.',
    likes: 245,
    saves: 134,
    views: 1980,
    author: 'LisbonLover',
    rating: 4.8,
    locations: 15,
  },
  {
    id: 'itinerary-17',
    type: 'itinerary',
    title: 'Cape Town Natural Beauty',
    destination: 'Cape Town, South Africa',
    duration: '5 days',
    description: 'Table Mountain, penguins, wine country, and the stunning Cape Peninsula.',
    likes: 267,
    saves: 145,
    views: 2050,
    author: 'CapeTownGuide',
    rating: 4.8,
    locations: 14,
  },
  {
    id: 'itinerary-18',
    type: 'itinerary',
    title: 'Stockholm Archipelago Explorer',
    destination: 'Stockholm, Sweden',
    duration: '4 days',
    description: 'Gamla Stan, museums, archipelago boat tours, and Scandinavian design.',
    likes: 189,
    saves: 98,
    views: 1450,
    author: 'NordicTraveler',
    rating: 4.6,
    locations: 12,
  },
]
