// 50 London locations for Discover page - sorted by popularity (review count)
export interface DiscoverLocation {
  id: string
  name: string
  category: string
  description: string
  rating: number
  reviews: number
  distance: string
  image?: string
  lat?: number // Pre-populated coordinates to avoid geocoding API calls
  lng?: number
}

export const discoverLocations: DiscoverLocation[] = [
  {
    id: '1',
    name: 'Tower of London',
    category: 'Historic Site',
    description: 'Historic castle and royal palace with the Crown Jewels',
    rating: 4.8,
    reviews: 12543,
    distance: '0.5 km',
    lat: 51.5081,
    lng: -0.0759,
  },
  {
    id: '2',
    name: 'British Museum',
    category: 'Museum',
    description: 'World-famous museum with vast collections of art and artifacts',
    rating: 4.7,
    reviews: 10987,
    distance: '1.2 km',
    lat: 51.5194,
    lng: -0.1270,
  },
  {
    id: '3',
    name: 'Buckingham Palace',
    category: 'Historic Site',
    description: 'Official residence of the British monarch',
    rating: 4.6,
    reviews: 15678,
    distance: '2.1 km',
    lat: 51.5014,
    lng: -0.1419,
  },
  {
    id: '4',
    name: 'Westminster Abbey',
    category: 'Historic Site',
    description: 'Gothic church and site of royal coronations',
    rating: 4.8,
    reviews: 11234,
    distance: '1.8 km',
    lat: 51.4994,
    lng: -0.1274,
  },
  {
    id: '5',
    name: 'London Eye',
    category: 'Attraction',
    description: 'Giant observation wheel on the South Bank',
    rating: 4.5,
    reviews: 9876,
    distance: '1.5 km',
    lat: 51.5033,
    lng: -0.1196,
  },
  {
    id: '6',
    name: 'Tate Modern',
    category: 'Museum',
    description: 'Modern art gallery in a former power station',
    rating: 4.7,
    reviews: 8765,
    distance: '0.8 km',
    lat: 51.5076,
    lng: -0.0994,
  },
  {
    id: '7',
    name: 'Natural History Museum',
    category: 'Museum',
    description: 'Museum showcasing natural history and dinosaurs',
    rating: 4.8,
    reviews: 10234,
    distance: '2.8 km',
    lat: 51.4967,
    lng: -0.1764,
  },
  {
    id: '8',
    name: 'Hyde Park',
    category: 'Park',
    description: 'Large royal park in central London',
    rating: 4.6,
    reviews: 7654,
    distance: '2.5 km',
    lat: 51.5073,
    lng: -0.1657,
  },
  {
    id: '9',
    name: 'Covent Garden',
    category: 'Shopping',
    description: 'Famous shopping and entertainment district',
    rating: 4.4,
    reviews: 8765,
    distance: '1.1 km',
    lat: 51.5125,
    lng: -0.1236,
  },
  {
    id: '10',
    name: 'St. Paul\'s Cathedral',
    category: 'Historic Site',
    description: 'Baroque cathedral with iconic dome',
    rating: 4.7,
    reviews: 6543,
    distance: '0.9 km',
    lat: 51.5138,
    lng: -0.0984,
  },
  {
    id: '11',
    name: 'Camden Market',
    category: 'Market',
    description: 'Vibrant market with food, fashion, and crafts',
    rating: 4.3,
    reviews: 5432,
    distance: '3.2 km',
    lat: 51.5416,
    lng: -0.1464,
  },
  {
    id: '12',
    name: 'Shakespeare\'s Globe',
    category: 'Theater',
    description: 'Reconstruction of the original Globe Theatre',
    rating: 4.6,
    reviews: 4321,
    distance: '1.0 km',
    lat: 51.5081,
    lng: -0.0972,
  },
  {
    id: '13',
    name: 'Borough Market',
    category: 'Market',
    description: 'Historic food market with gourmet vendors',
    rating: 4.5,
    reviews: 5678,
    distance: '0.7 km',
    lat: 51.5055,
    lng: -0.0907,
  },
  {
    id: '14',
    name: 'Kensington Palace',
    category: 'Historic Site',
    description: 'Royal residence with beautiful gardens',
    rating: 4.4,
    reviews: 3456,
    distance: '3.1 km',
    lat: 51.5050,
    lng: -0.1878,
  },
  {
    id: '15',
    name: 'Victoria and Albert Museum',
    category: 'Museum',
    description: 'Museum of art, design, and performance',
    rating: 4.7,
    reviews: 7890,
    distance: '2.6 km',
    lat: 51.4966,
    lng: -0.1722,
  },
  {
    id: '16',
    name: 'Tower Bridge',
    category: 'Landmark',
    description: 'Iconic bascule bridge over the Thames',
    rating: 4.6,
    reviews: 6789,
    distance: '0.6 km',
    lat: 51.5055,
    lng: -0.0754,
  },
  {
    id: '17',
    name: 'Big Ben',
    category: 'Landmark',
    description: 'Famous clock tower and symbol of London',
    rating: 4.7,
    reviews: 8901,
    distance: '1.9 km',
    lat: 51.4994,
    lng: -0.1245,
  },
  {
    id: '18',
    name: 'Piccadilly Circus',
    category: 'Landmark',
    description: 'Famous public space and traffic intersection',
    rating: 4.3,
    reviews: 4567,
    distance: '1.4 km',
    lat: 51.5101,
    lng: -0.1340,
  },
  {
    id: '19',
    name: 'Regent\'s Park',
    category: 'Park',
    description: 'Royal park with London Zoo and rose gardens',
    rating: 4.5,
    reviews: 3210,
    distance: '2.9 km',
    lat: 51.5232,
    lng: -0.1544,
  },
  {
    id: '20',
    name: 'National Gallery',
    category: 'Museum',
    description: 'Art museum with European paintings',
    rating: 4.7,
    reviews: 9012,
    distance: '1.6 km',
    lat: 51.5089,
    lng: -0.1283,
  },
  {
    id: '21',
    name: 'Greenwich Park',
    category: 'Park',
    description: 'Historic park with Royal Observatory',
    rating: 4.4,
    reviews: 2345,
    distance: '5.2 km',
    lat: 51.4769,
    lng: -0.0005,
  },
  {
    id: '22',
    name: 'Hampton Court Palace',
    category: 'Historic Site',
    description: 'Tudor palace with beautiful gardens and maze',
    rating: 4.6,
    reviews: 3456,
    distance: '15.3 km',
    lat: 51.4036,
    lng: -0.3378,
  },
  {
    id: '23',
    name: 'Royal Albert Hall',
    category: 'Venue',
    description: 'Concert hall with stunning architecture',
    rating: 4.5,
    reviews: 4567,
    distance: '2.7 km',
    lat: 51.5010,
    lng: -0.1774,
  },
  {
    id: '24',
    name: 'Portobello Road Market',
    category: 'Market',
    description: 'Famous antiques market in Notting Hill',
    rating: 4.4,
    reviews: 5678,
    distance: '3.8 km',
    lat: 51.5151,
    lng: -0.1950,
  },
  {
    id: '25',
    name: 'Kew Gardens',
    category: 'Park',
    description: 'Botanical gardens with glasshouses',
    rating: 4.7,
    reviews: 6789,
    distance: '8.5 km',
    lat: 51.4846,
    lng: -0.2957,
  },
  {
    id: '26',
    name: 'Madame Tussauds',
    category: 'Attraction',
    description: 'Wax museum with celebrity figures',
    rating: 4.2,
    reviews: 7890,
    distance: '1.3 km',
    lat: 51.5230,
    lng: -0.1544,
  },
  {
    id: '27',
    name: 'Thames River Cruise',
    category: 'Activity',
    description: 'Scenic boat tours along the Thames',
    rating: 4.5,
    reviews: 3456,
    distance: '0.4 km',
    lat: 51.5074,
    lng: -0.1278,
  },
  {
    id: '28',
    name: 'Leadenhall Market',
    category: 'Market',
    description: 'Victorian covered market',
    rating: 4.3,
    reviews: 2345,
    distance: '0.8 km',
    lat: 51.5133,
    lng: -0.0836,
  },
  {
    id: '29',
    name: 'Sky Garden',
    category: 'Attraction',
    description: 'Public garden with panoramic city views',
    rating: 4.6,
    reviews: 5678,
    distance: '0.7 km',
    lat: 51.5115,
    lng: -0.0839,
  },
  {
    id: '30',
    name: 'Churchill War Rooms',
    category: 'Museum',
    description: 'Underground WWII command center',
    rating: 4.7,
    reviews: 4321,
    distance: '1.7 km',
    lat: 51.5021,
    lng: -0.1293,
  },
  {
    id: '31',
    name: 'Shakespeare\'s Birthplace',
    category: 'Historic Site',
    description: 'Historic house in Stratford-upon-Avon',
    rating: 4.5,
    reviews: 3210,
    distance: '120 km',
    lat: 52.1923,
    lng: -1.7074,
  },
  {
    id: '32',
    name: 'Stonehenge',
    category: 'Historic Site',
    description: 'Prehistoric stone circle',
    rating: 4.4,
    reviews: 2109,
    distance: '130 km',
    lat: 51.1789,
    lng: -1.8262,
  },
  {
    id: '33',
    name: 'Windsor Castle',
    category: 'Historic Site',
    description: 'Oldest occupied castle in the world',
    rating: 4.7,
    reviews: 5432,
    distance: '32 km',
    lat: 51.4839,
    lng: -0.6044,
  },
  {
    id: '34',
    name: 'Oxford Street',
    category: 'Shopping',
    description: 'Famous shopping street',
    rating: 4.2,
    reviews: 6543,
    distance: '1.5 km',
    lat: 51.5150,
    lng: -0.1419,
  },
  {
    id: '35',
    name: 'Harrods',
    category: 'Shopping',
    description: 'Luxury department store',
    rating: 4.4,
    reviews: 7654,
    distance: '2.3 km',
    lat: 51.4995,
    lng: -0.1634,
  },
  {
    id: '36',
    name: 'Notting Hill',
    category: 'Neighborhood',
    description: 'Colorful neighborhood with Portobello Market',
    rating: 4.5,
    reviews: 4321,
    distance: '3.9 km',
    lat: 51.5151,
    lng: -0.1962,
  },
  {
    id: '37',
    name: 'Soho',
    category: 'Neighborhood',
    description: 'Vibrant entertainment district',
    rating: 4.3,
    reviews: 3210,
    distance: '1.2 km',
    lat: 51.5133,
    lng: -0.1327,
  },
  {
    id: '38',
    name: 'The Shard',
    category: 'Landmark',
    description: 'Tallest building in London with viewing platform',
    rating: 4.5,
    reviews: 8901,
    distance: '0.9 km',
    lat: 51.5045,
    lng: -0.0865,
  },
  {
    id: '39',
    name: 'Millennium Bridge',
    category: 'Landmark',
    description: 'Pedestrian bridge connecting St. Paul\'s to Tate Modern',
    rating: 4.4,
    reviews: 2345,
    distance: '0.8 km',
    lat: 51.5095,
    lng: -0.0983,
  },
  {
    id: '40',
    name: 'Trafalgar Square',
    category: 'Landmark',
    description: 'Public square with Nelson\'s Column',
    rating: 4.5,
    reviews: 5678,
    distance: '1.5 km',
    lat: 51.5081,
    lng: -0.1281,
  },
  {
    id: '41',
    name: 'Leicester Square',
    category: 'Landmark',
    description: 'Entertainment hub with cinemas and theaters',
    rating: 4.2,
    reviews: 3456,
    distance: '1.3 km',
    lat: 51.5103,
    lng: -0.1301,
  },
  {
    id: '42',
    name: 'Brick Lane',
    category: 'Neighborhood',
    description: 'Famous for curry houses and street art',
    rating: 4.4,
    reviews: 4567,
    distance: '2.2 km',
    lat: 51.5193,
    lng: -0.0719,
  },
  {
    id: '43',
    name: 'Spitalfields Market',
    category: 'Market',
    description: 'Historic market with food and crafts',
    rating: 4.3,
    reviews: 2109,
    distance: '2.0 km',
    lat: 51.5200,
    lng: -0.0750,
  },
  {
    id: '44',
    name: 'Hampstead Heath',
    category: 'Park',
    description: 'Large park with swimming ponds and views',
    rating: 4.6,
    reviews: 3210,
    distance: '5.8 km',
    lat: 51.5555,
    lng: -0.1653,
  },
  {
    id: '45',
    name: 'Richmond Park',
    category: 'Park',
    description: 'Largest royal park with deer',
    rating: 4.5,
    reviews: 2345,
    distance: '12.5 km',
    lat: 51.4494,
    lng: -0.2720,
  },
  {
    id: '46',
    name: 'Primrose Hill',
    category: 'Park',
    description: 'Hill with panoramic views of London',
    rating: 4.4,
    reviews: 1234,
    distance: '4.2 km',
    lat: 51.5367,
    lng: -0.1594,
  },
  {
    id: '47',
    name: 'Columbia Road Flower Market',
    category: 'Market',
    description: 'Sunday flower market in East London',
    rating: 4.5,
    reviews: 1098,
    distance: '3.1 km',
    lat: 51.5273,
    lng: -0.0720,
  },
  {
    id: '48',
    name: 'Neal\'s Yard',
    category: 'Neighborhood',
    description: 'Colorful courtyard in Covent Garden',
    rating: 4.3,
    reviews: 987,
    distance: '1.0 km',
    lat: 51.5150,
    lng: -0.1250,
  },
  {
    id: '49',
    name: 'Little Venice',
    category: 'Neighborhood',
    description: 'Picturesque canal area',
    rating: 4.4,
    reviews: 876,
    distance: '4.5 km',
    lat: 51.5230,
    lng: -0.1830,
  },
  {
    id: '50',
    name: 'Highgate Cemetery',
    category: 'Historic Site',
    description: 'Victorian cemetery with famous graves',
    rating: 4.5,
    reviews: 765,
    distance: '6.2 km',
    lat: 51.5673,
    lng: -0.1447,
  },
]
